# Generated by Django 3.1.1 on 2020-10-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.CharField(choices=[('PER', 'Person'), ('POL', 'Policy'), ('GOV', 'Government'), ('COU', 'Country'), ('WOR', 'Work'), ('PHI', 'Philosophy'), ('OTH', 'Other')], max_length=3),
        ),
    ]
