# Generated by Django 3.1.1 on 2020-11-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntc', '0002_auto_20201030_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.CharField(choices=[('PER', 'Person'), ('POL', 'Policy'), ('GOV', 'Government'), ('COU', 'Country'), ('OTH', 'Other')], max_length=3),
        ),
    ]
