# Generated by Django 3.1.1 on 2021-05-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntc', '0004_auto_20210523_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='ntc/default.svg', upload_to='ntc/'),
        ),
    ]
