# Generated by Django 3.1.1 on 2021-05-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntc', '0005_auto_20210523_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.CharField(choices=[('PER', 'Person'), ('POL', 'Policy'), ('GOV', 'Government'), ('COU', 'Country'), ('PHI', 'Philosophy'), ('WOR', 'Work'), ('OTH', 'Other')], max_length=3),
        ),
    ]
