# Generated by Django 3.1.1 on 2021-11-12 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntc', '0006_auto_20210525_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntc.profile')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntc.topic')),
            ],
        ),
    ]
