# Generated by Django 3.1.1 on 2022-03-30 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntc', '0007_skip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skip',
            name='x',
        ),
        migrations.RemoveField(
            model_name='skip',
            name='y',
        ),
    ]
